# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App9
  pod 'Alamofire'

  target 'App9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'App9UITests' do
    # Pods for testing
  end

end
